import Head from "next/head";

import { GoogleSpreadsheet } from "google-spreadsheet";

import styles from "../styles/Home.module.css";

export default function Home({ title }) {
  console.log(title);

  return (
    <div className={styles.container}>
      <Head>
        <title>Leyendo {title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Leyendo {title}</h1>
      </main>
    </div>
  );
}

export async function getStaticProps(_context) {
  console.log(process.env.GOOGLE_SHEET_ID);
  const sheet = new GoogleSpreadsheet(process.env.GOOGLE_SHEET_ID);

  await sheet.useServiceAccountAuth({
    client_email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
    private_key: process.env.GOOGLE_PRIVATE_KEY,
  });

  await sheet.loadInfo();

  return {
    props: {
      title: sheet.title,
    },
  };
}
